version: '3.9'

services:
  # Backend Service
  backend:
    container_name: backend
    env_file: 
      - ./config.env
    restart: always
    build: ./src/
    ports:
      - "5000:5000"
    volumes:
      - ./src/:/home/app/
    command: setup.py -s backend