FROM python:3.9.4-slim as build

WORKDIR /wheels

RUN apt update && apt install curl -y && apt install gnupg -y
RUN apt install gcc -y && apt install g++ -y

COPY requirements.txt /opt/displayer/requirements.txt
RUN pip3 wheel -r /opt/displayer/requirements.txt

# Main docker image to be built
FROM python:3.9.4-slim

RUN adduser nonroot
RUN mkdir /home/app/ && chown -R nonroot:nonroot /home/app
WORKDIR /home/app

COPY --from=build /wheels /wheels
COPY --chown=nonroot:nonroot requirements.txt /home/app/
RUN pip3 install -r requirements.txt -f /wheels \
  && rm -rf /wheels \
  && rm -rf /root/.cache/pip/* \
  && rm requirements.txt

RUN apt-get update
RUN apt-get install -y pngcrush

# Setup font(s)
RUN apt-get -y install fontconfig
COPY ./fonts/courbd.ttf /opt/displayer/courbd.ttf
RUN mkdir -p /usr/share/fonts/courbd/
RUN install -m644 /opt/displayer/courbd.ttf /usr/share/fonts/courbd/
RUN rm /opt/displayer/courbd.ttf
RUN fc-cache -f -v

# Configure TimeZone
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

USER nonroot

# Feyre.py
COPY --chown=nonroot:nonroot . /home/app/

ENTRYPOINT [ "python" ]
