# Main docker image to be built
FROM python:3.9.4-slim

RUN adduser nonroot
RUN mkdir /home/app/ && chown -R nonroot:nonroot /home/app
WORKDIR /home/app

COPY --from=build /wheels /wheels
COPY --chown=nonroot:nonroot requirements.txt /home/app/
RUN pip3 install -r requirements.txt -f /wheels \
  && rm -rf /wheels \
  && rm -rf /root/.cache/pip/* \
  && rm requirements.txt

USER nonroot

# Feyre.py
COPY --chown=nonroot:nonroot . /home/app/

ENTRYPOINT [ "python" ]
